// Underscore id (_id) are autogenerated ID from mongoDB, we are not here to pass any id
class IssuedBook {
    _id;
    name;
    author;
    genre;
    price;
    publisher;
    issuedBy;
    issuedDate;
    returnDate;
// Constructor doesn't return anything
// Whenever we create obj,the constructor gets invoked - (parameterized constructor)
constructor(user){
    this._id = user.issuedBook._id;
    this.name = user.issuedBook.name;
    this.author = user.issuedBook.author;
    this.genre = user.issuedBook.genre;
    this.price = user.issuedBook.price;
    this.publisher = user.issuedBook.publisher;
    this.issuedBy = user.issuedBy;
    this.issuedDate = user.issuedDate;
    this.returnDate = user.returnDate;
}
}

module.exports = IssuedBook;

